name: KnockbackFFA
main: ItzLightyHD\KnockbackFFA\Loader
api: 5.0.0
version: 1.0.0
authors:
  - ItzLightyHD
  - OwoNico
permissions:
  knockbackffa.customize:
    default: op
  knockbackffa.player:
    default: true
